### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#13]
Hello, thank you for the addon ! 
1) How can i change lightmap resolution ? 
2) Can i bake whole scene into one lightmap? 
3) How can i use OIDN? i get error - 
![image](https://user-images.githubusercontent.com/22406105/76160601-91301180-613c-11ea-8f56-b9d79d2350b9.png)
4) Clean lightmap cache not working, i should manually clean graph node for every object
5) Filtering is not working too ( 
![image](https://user-images.githubusercontent.com/22406105/76160643-e66c2300-613c-11ea-99ea-4141871cd6db.png)

**Comment by Naxela** [comment]
Hi, - Thank you for trying out the addon

1. The resolution is set individually for each object - By default it's 256, but the values goes between 32 to 8192:

![Resolution](https://user-images.githubusercontent.com/5429817/76162783-f7b72e80-6140-11ea-952f-1eb9fc608ef7.jpg)

2. Yes, in the latest WIP version, you just need to select all objects in the same (A), and select **Enable for selection** in the selection panel - Additionally, you can set the lightmap resolution for all objects by selecting **override settings**:

![WholeScene](https://user-images.githubusercontent.com/5429817/76162824-51b7f400-6141-11ea-87ea-d816715778f9.jpg)

3. / 4. / 5. - The problems exists in the first release (when it was called HDR Lightmapper / HDRLM) - You can get the latest version by cloning from the master branch, or download zip from here: https://github.com/Naxela/The_Lightmapper/archive/master.zip - You'll need to download the OIDN/Denoiser package separately, get it here: https://github.com/OpenImageDenoise/oidn/releases/download/v1.1.0/oidn-1.1.0.x64.vc14.windows.zip (Windows)

You just need to set the path to the bin folder, when you unpack the denoise folder

![OIDN](https://user-images.githubusercontent.com/5429817/76162909-271a6b00-6142-11ea-81ee-3b0502d39111.jpg)


Please tell if it helped, thanks

**Comment by koloved** [comment]
OH, thank you for the answer ! 
All of the parameters now work ! except for the bake into one map
i select all objects then ' Enable for selection " then override map resolution and it still have separate maps (

and i have two questions - 
can the addon use existence  uv1 for baking maps ? if not can you add option for it ? 
can the addon use existence oidn implementation ? result are the same , you can decrease the size of the addon
![image](https://user-images.githubusercontent.com/22406105/76169467-88b1f800-6189-11ea-8db2-47619ac96c21.png)

**Comment by Naxela** [comment]
Hi, 

I misunderstood your second question. As for baking everything into one map, it's not yet available but atlasing (merging into one big shared map through uv) is on the todo list: https://github.com/Naxela/The_Lightmapper/issues/15#issue-577550280

As for your two questions - If you've an existing uvmap you can select the **Copy Existing** option under the unwrap mode - I think it should use UVMap:

![copy_existing](https://user-images.githubusercontent.com/5429817/76169621-50ef8400-617a-11ea-84c2-1912f0684c1e.jpg)

As for the existing OIDN it seems to be without any external bindings, plus I think they use different OIDN filters - Blender probably uses the RT filter, where this lightmapping uses "RTLightmap" filter, made specifically for lightmapping.

**Comment by Naxela** [comment]
It is now possible to bake multiple objects into the same textures with Atlas baking
