### ISSUE TITLE
copy node

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#14]
its create the same node every time when i click "build light"
![image](https://user-images.githubusercontent.com/22406105/76160841-a1e18700-613e-11ea-86e0-3825efce411e.png)
![image](https://user-images.githubusercontent.com/22406105/76160846-aefe7600-613e-11ea-85e3-f4de438c8924.png)
after it when i press "build light" again it turns into black
![image](https://user-images.githubusercontent.com/22406105/76160862-d05f6200-613e-11ea-8f40-bf4866be995b.png)

**Comment by Naxela** [comment]
Hi,

If you try it with the newest work-in-progress mentioned here: https://github.com/Naxela/The_Lightmapper/issues/13#issuecomment-596201231 - It should now be called The Lightmapper - It should be a little more stable to use

I'll make a new release in the future along with some better documentation
