### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [Naxela/The_Lightmapper#140]
Hi.

There is a license text in the __init__ file. Is it intended to apply to the whole repository? If so, I suggest adding it as a LICENSE file.
If not, what is the overall license for the repository?

There used to be a LICENSE file with GPLv3, but is now removed.

**Comment by Naxela** [comment]
Hi,

Sorry about the late reply. Yes, the addon is supposed to be GPL (either v2 or v3, not sure which one Blender uses). The only exception is the external rectangle packing library rectpack (https://github.com/secnot/rectpack): https://github.com/Naxela/The_Lightmapper/tree/master/addon/utility/rectpack - It seems that uses Apache 2.0. Although that's only necessary if you're using the atlas post-packing utility.

**Comment by Aspie96** [comment]
Hi, @Naxela.

I am not a lawyer and this is not legal advice.

> either v2 or v3, not sure which one Blender uses

Blender as a whole uses version 3, although most of the Blender source code uses "v2 or later".

Please see: https://www.blender.org/about/license/
> The source code we develop at blender.org is default being licensed as GNU GPL Version 2 or later.

Apache 2.0 will not be a problem, and it's also what Cycles uses. Apache 2.0 is incompatible with GPL 2, but fully compatible with GPL 3.

So the license you should be using is GPL 3, or a compatible license. I suggest that you use "GPL v3 or later", for better future compatibility, although you do not have to. This is also the license used by other extensions: https://github.com/CGCookie/retopoflow

**Comment by Naxela** [comment]
Hi, I've set it to be the same license as Blender, meaning GPL 3: https://github.com/Naxela/The_Lightmapper/tree/master

**Comment by Aspie96** [comment]
Thank you, @Naxela.
If I may give you a suggestion, consider "GPLv3 or later" instead of "GPLv3 only".
The advantage is future compatibility in case GPLv4 is ever published.

Suppose a bad GPLv4 is published, with a loophole. The FLOSS community can simply switch projects from "GPLv3 or later" to "GPLv3 only" and those wanting to use that loophole will be stuck with old projects.
Suppose, however, that something happens which makes GPLv3 weaker (as happened with GPLv2) and a new GPLv4 is published. Projects under "GPLv3 only" cannot be switched to "GPLv4" and remain stuck.

This also works better in case the license Blender itself ever becomes GPLv4.

For those that do not trust the FSF and fear it might publish a bad (or very different) GPLv4, the GPLv3 also has a proxy mechanism: you can nominate a party (yourself included) which determines what future versions of the GPL are valid for the project.
I think the FSF can be trusted with future versions of the GPL, and that it's generally better to avoid the proxy mechanism, but it's still better than "GPLv3 only".

Regardless, the issue is solved.
