### ISSUE TITLE
errors when using ArchiPack pack models and atlas maps

### ISSUE THREAD

**Issue by Marwan0** [Naxela/The_Lightmapper#152]
using Blender 3.1
![Blender  DTest Lightmaper blend](https://user-images.githubusercontent.com/6762563/172080683-6cdbec4d-597f-4328-a4db-28d7681c4393.jpg)

**Comment by Naxela** [comment]
Hi,

I don't have ArchiPack so I'm not sure how to the materials are setup in the model, but it might seem like there isn't any materials applied
