### ISSUE TITLE
Todo: Fix setup for Blender 3.3

### ISSUE THREAD

**Issue by Naxela** [Naxela/The_Lightmapper#157]
On Blender 3.3 some settings have been changed, investigate which - Something clamped to sRGB / non-linear:
![image](https://user-images.githubusercontent.com/5429817/189548664-aae7b5e7-6a0e-41d7-9520-6b6d1676f6bf.png)

On Blender 3.2/3.1 (Works):
![image](https://user-images.githubusercontent.com/5429817/189548673-3e315f27-1456-4314-afd7-cb0f40931c1f.png)

**Comment by ArtyIF** [comment]
Is this related to the issue I'm having?

Rendered in Cycles:

![Reference](https://user-images.githubusercontent.com/8017858/197415582-403d8b99-3744-495c-b670-c5954ef26307.png)

Rendered with lightmaps, DiffCol only:

![ActualResult](https://user-images.githubusercontent.com/8017858/197415593-0001600e-b829-4e0a-b6db-975c0ccd36e4.png)

**Comment by Naxela** [comment]
Hi, sorry about the late answer. Yes, I do think it was related to some of the colorspace settings that was changed in 3.3.
