### ISSUE TITLE
disgusting result (high and production quality)

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#16]
i dont know why but sometimes when i use high and production quality i get this result

![image](https://user-images.githubusercontent.com/22406105/76320444-c336a480-62f1-11ea-905c-8dfed80193bb.png)

sometimes I always get this result on these settings, sometimes I don't get it.
sometimes the map is just white, but if I choose the quality is low and the medium is always good. 
![image](https://user-images.githubusercontent.com/22406105/76321616-54f2e180-62f3-11ea-8296-f2bed3bdccbb.png)

**Comment by Naxela** [comment]
Hi,

That sounds quite strange - thanks for reporting the bug.

I haven't come across this bug myself before - Could you by any chance share the .blend file or the material setup?

The only difference between medium to production/high should be an increased amount of samples, along with enabled caustics - Does it have any difference if you use CPU?

Also, do you get any console warnings?

**Comment by koloved** [comment]
i had this before on another scene.
no one material in the scene
cpu and gpu  - same result

i found the way
its happens every time when scene has at least 1 applayed lightmap on a other object
when i click clean lightmaps every time before bake is everything ok

**Comment by Naxela** [comment]
Hi, I was able to reproduce - I'll look into fixing it: https://github.com/Naxela/The_Lightmapper/issues/17

**Comment by Naxela** [comment]
This might have been fixed with https://github.com/Naxela/The_Lightmapper/commit/ac11ba087c2d22cbc006a695836681a80dedc142 - It should work now

**Comment by koloved** [comment]
thank you!
