### ISSUE TITLE
strange artifacts with denoise activated

### ISSUE THREAD

**Issue by dirkk0** [Naxela/The_Lightmapper#169]
Hi!

First of all - thank you for this tool, it's fantastic!

Then: I experimentally switched from Blender 3.3 to the latest 3.5.1.
The good news is - it still works!
The not so good news is: activating the integrated denoiser results in (presumably) mixed up images, like so:
![2023-04-28_16-00](https://user-images.githubusercontent.com/625394/235169360-dd2a100b-76b1-409c-9311-eb059284336b.png)

Without the denoiser, it looks like that:
![2023-04-28_16-01](https://user-images.githubusercontent.com/625394/235169443-e2fc0ae7-4973-4442-b7f0-2094c52594e2.png)

Doing the same in Blender 3.3 (add plane and icosphere, acivate lightmapper for the whole scene, add denoise) works perfectly.

I wonder why that is?

Thanks again, Dirk

PS: I can provide the files if needed.

**Comment by Naxela** [comment]
Hi, thanks for checking this out. There definitely seems to be a bug with the internal denoiser (they've probably changed something between 3.3 and 3.5 related to the compositor). In the meantime, can you check if manually using OIDN works? (Package from here: https://github.com/OpenImageDenoise/oidn/releases)

Thanks again!

**Comment by Naxela** [comment]
Hi again, I think I might have fixed the issue now - Could you test if it works for you now?

Thanks

**Comment by dirkk0** [comment]
works like a charm! thanks!

**Comment by victorbnl** [comment]
I had this issue as well. If OIDN can be used as a workaround, shouldn’t this issue be kept open to further investigate on why Blender’s standard denoiser acts like that, and what should be done in consequence?
