### ISSUE TITLE
Default dilation margin make noise lightmap

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#18]
Probably denoiser dont understand a border of UV island and take additional space of margin when denoiser work and make the bad result 
![Screenshot_8](https://user-images.githubusercontent.com/22406105/77014741-080eab00-6984-11ea-89dc-3df050ffce6b.jpg)

**Comment by Naxela** [comment]
I've decreased the default dilation margin to 2px now - I might look into some kind of denoising masks in the future, based on the UV map
