### ISSUE TITLE
Stopped working in 4.2

### ISSUE THREAD

**Issue by DavidFenk** [Naxela/The_Lightmapper#189]
Still works in 4.1 though. Any fixes/updates planned in the near future? For me, there is no better baking addon out there!

**Comment by Naxela** [comment]
Hi, do you get any specific errors in 4.2? - I'm using it right now in 4.2 and it works fine on my end

Oh by the way, are you using the package/release from 2022, or the latest git version?

**Comment by DavidFenk** [comment]
Thanks for the fast reply! This is the error I get in 4.2 (4.2.1 to be precise) but not in 4.1. Maybe a different problem? It's the release from 2022.

![image](https://github.com/user-attachments/assets/f50d4a57-f87e-45bb-8f1f-d170d760f372)

**Comment by Naxela** [comment]
I usually only work with git commits, and haven't made any releases for a while. Normally I just refer people to the latest git commit, but it was probably about time for a new one anyway - could you try it out and see if it works?:

https://github.com/Naxela/The_Lightmapper/releases/tag/0.7.0

**Comment by DavidFenk** [comment]
Unfortunately it's still not working for me.

![image](https://github.com/user-attachments/assets/12a3f183-3cb2-4d7a-abfe-58cba81a8de3)

**Comment by Naxela** [comment]
I haven't been able to reproduce it on my end, what's confusing is that the line doesn't have any references to the gui setting (https://github.com/Naxela/The_Lightmapper/blob/2b4feb63f60719c0d18301ae1392eaedb77f353a/addon/utility/build.py#L1319)

Does it make a difference if you don't have verbose mode toggled on?

If not, could you try removing thelightmapper addon folder, and try the latest git version?: https://github.com/Naxela/The_Lightmapper/archive/refs/heads/master.zip

**Comment by DavidFenk** [comment]
Ok, I just tried again with a blank new Blender scene and it works there with simple settings. So, it might be some scene setting carried over from earlier version of Blender which makes your last suggestion sound promising. Need some time to investigate. Thanks for your fast help so far! Going to get back to you asap with new insights.

**Comment by DavidFenk** [comment]
Hi Naxela! Everything works now. Seems I had a problem when installing the addon for the new version. Mistake on my side. Thanks again for the support, and sorry for the inconvenience. Best, David
