### ISSUE TITLE
EXR Support

### ISSUE THREAD

**Issue by astrand130** [Naxela/The_Lightmapper#20]
It would be nice if the addon could export to Open EXR as well. Many texture processing pipelines (such as ones using AMD's Compressionator) don't support .hdr files.

**Comment by Naxela** [comment]
Hi, that should be easy to add. I'll put it on my todo list!

**Comment by Naxela** [comment]
I've added support for this in the latest commit (https://github.com/Naxela/The_Lightmapper/commit/4e85bb101bd084dca457f8443b74fcdf7440363e):

![billede](https://user-images.githubusercontent.com/5429817/81079355-c1ebb780-8eef-11ea-96c0-18cd457d4dc6.png)
