### ISSUE TITLE
UV unwrap broken

### ISSUE THREAD

**Issue by Simonrazer** [Naxela/The_Lightmapper#3]
In the options for the individual objects, there are UV option. You can choose Smart, Lightmap, or Copy. Smart and Lightmap unfortunately produce the same broken result, where some faces are squeezed into zero-width/height faces on the UV map. Copy works fine. Win10 b2.81a

**Comment by Naxela** [comment]
Hi, thanks for reporting

By default it should use the same unwrapping algorithms as used in Blender - I've come across the same problem with faces that are squeezed into too small UV islands, but applying transforms (Object > Apply > Scale and Rotation) to the mesh after editing seems to fix most of these issues before baking:

![Example1](https://user-images.githubusercontent.com/5429817/71768215-7959c880-2f14-11ea-9563-fd03cb065493.jpg)

![Example2](https://user-images.githubusercontent.com/5429817/71768216-7c54b900-2f14-11ea-974e-94d6729fbd69.jpg)

Although this can be pretty time-consuming for scenes with a lot of objects, so there's the option to apply scale before baking, but for some reason this doesn't seem to work always:

![ScaleApply](https://user-images.githubusercontent.com/5429817/71768275-03099600-2f15-11ea-946c-bb6bd5016b8b.jpg)

I plan on exposing more of the uv mapping paramaters too, and possibly adding support for other UV mapping addons or applications like RizomUV or UVPackmaster (although I'm generally not fond of the latter idea)
