### ISSUE TITLE
LogLuv 8 bit encoded looks weird

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#31]
i use the settings
![image](https://user-images.githubusercontent.com/22406105/83951848-473ef080-a83d-11ea-84fe-56d8f4bc90cf.png)

**Comment by Naxela** [comment]
Yeah that's what it looks like when it's encoded to an 8-bit with the information transformed into an other color space - If you toggle on the "Armory decoder" does it look fine?
