### ISSUE TITLE
Crash with Blender 2.83

### ISSUE THREAD

**Issue by ThomasRadeke** [Naxela/The_Lightmapper#32]
After installing the add-on on Blender 2.83 and clicking the "Build Light for selected" button, the process crashes with this message:

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\HDR_Lightmapper\__init__.py", line 449, in execute
    HDRLM_Build(self, context)
  File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\HDR_Lightmapper\__init__.py", line 1585, in HDRLM_Build
    mainNode = nodetree.nodes[0].inputs[0].links[0].from_node
IndexError: tuple index out of range

It works with 2.82.

**Comment by Naxela** [comment]
Hi, it seems like you're using version 0.1 from the release pages - If you download the latest git version, either from Clone or from here: https://github.com/Naxela/The_Lightmapper/archive/master.zip - It should work - Or if you can wait a few minutes, I'll have a 0.2 release up to download along with a Bundled OIDN denoiser

**Comment by Naxela** [comment]
Added a new release - It should work with 2.83 too now: https://github.com/Naxela/The_Lightmapper/releases

**Comment by ThomasRadeke** [comment]
Yes, I was indeed using the release. It works now - thank you very much for your effort!
