### ISSUE TITLE
Can't make the OIDN working

### ISSUE THREAD

**Issue by GHOZALI1** [Naxela/The_Lightmapper#36]
Hi, i just recently found this addon, and really help, but my main problem is i can't get the OIDN denoiser working, how to use the OIDN? Where do i put OIDN Path? 
I'm using windows 10, blender 2.83

Thank you

**Comment by Naxela** [comment]
Hi, thank you for trying out the addon!
For the oidn path you just need to point to the actual folder rather than the .exe file, although at this point I'm redoing it and it might be better at this point to try the 0.3 branch version - it uses the integrated denoising: https://github.com/Naxela/The_Lightmapper/tree/0.3

Hope it works!

**Comment by GHOZALI1** [comment]
Hi, thank you for your reply

i'm sorry, what do you mean by the actual folder? i tried put it in  **"%appdata%/Blender Foundation/Blender/2.82/scripts/addons/thelightmapper"** (but of course in my own directory, but it always shows error messages

is blender version might be the issue?

and for the 0.3 branch version, i got this error when try to check the checkbox in addon tab.

Traceback (most recent call last):
  File "C:\Users\ahmad\Documents\blender-2.83.2\blender-2.83.2-windows64\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'The_Lightmapper-0'

Why is this showing?

Thank you

**Comment by Naxela** [comment]
For the 0.2 version, there could be an error with the naming of the denoising exe file (I think the name was changed from denoise.exe in earlier versions of OIDN).

For the 0.3 version, can you check the folder name of the lightmapper? It should be "thelightmapper", but it might get unpacked as something else, if you check in the addon folder

**Comment by alexisstrat** [comment]
> 
> 
> Hi, thank you for your reply
> 
> i'm sorry, what do you mean by the actual folder? i tried put it in **"%appdata%/Blender Foundation/Blender/2.82/scripts/addons/thelightmapper"** (but of course in my own directory, but it always shows error messages
> 
> is blender version might be the issue?
> 
> and for the 0.3 branch version, i got this error when try to check the checkbox in addon tab.
> 
> Traceback (most recent call last):
> File "C:\Users\ahmad\Documents\blender-2.83.2\blender-2.83.2-windows64\2.83\scripts\modules\addon_utils.py", line 351, in enable
> mod = **import**(module_name)
> ModuleNotFoundError: No module named 'The_Lightmapper-0'
> 
> Why is this showing?
> 
> Thank you

For the 0.3 version name the folder's addon as the log says, "The_Lightmapper"
