### ISSUE TITLE
nodetree.nodes[0] in utility.py pointing at wrong node

### ISSUE THREAD

**Issue by Simonrazer** [Naxela/The_Lightmapper#4]
From my understanding, this term should always be pointing at the Material Output node. It does so most of the time correctly. But for some materials it points to a seemingly arbitrary node of the node tree. I modified utility.py starting at line 536 a bit to see what is going on:
```
for slot in obj.material_slots:
                    nodetree = bpy.data.materials[slot.name].node_tree
                    nodes = nodetree.nodes
                    print(slot.name)
                    #mainNode = nodetree.nodes[0].inputs[0].links[0].from_node
                    ab = nodetree.nodes[0]
                    print(ab)
                    ac = ab.inputs[0]
                    ad = ac.links[0]
                    mainNode = ad.from_node
```
This is the output, the first couple are for materials where no issues occur and then there is an error:
```
slot56_slot1_temp
<bpy_struct, ShaderNodeOutputMaterial("Material Output")>
slot60_slot1_temp
<bpy_struct, ShaderNodeOutputMaterial("Material Output")>
slot104_slot1_temp
<bpy_struct, ShaderNodeBump("Bump")>
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\The_Lightmapper-master\Addon\Operators\build.py", line 52, in modal
    utility.bake_ordered(self, context, None)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\The_Lightmapper-master\Addon\Utility\utility.py", line 1409, in bake_ordered
    configure_objects(scene)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\The_Lightmapper-master\Addon\Utility\utility.py", line 545, in configure_objects
    ad = ac.links[0]
IndexError: tuple index out of range

location: <unknown location>:-1 
```
Rebuilding the regarding Material -> deleting the nodes and placing them in the exact same way again, fixes the issue for this Material! 
Here a .blend where this occurs, the error should simply occur when you press Build Lightmaps.
https://drive.google.com/open?id=1Ys3pMuyKMM3GweP6X-hXO5H5gAo5lOJF
b2.81 Win10

**Comment by Naxela** [comment]
Thanks for reporting this,

It seems that in some cases the material output node might not always be the first in the series of the node list - shouldn't normally be the case, but if the blend has been converted between versions or changed between renderers (from LuxCoreRender to Cycles) and even sometimes being appended it'll shift the row

Anyway, added some fallbacks to search for the material output - If you've multiple material outputs and the active one is the second on the list it'll still throw and error I think.

Thanks for the .blend - It works now, I low key expected the multiple materials to break the lightmapper, but to my surprise it worked just fine:

![Outside](https://user-images.githubusercontent.com/5429817/71839993-b660bf00-30bc-11ea-8d79-8cc72f67010f.png)

![Inside1](https://user-images.githubusercontent.com/5429817/71840001-b9f44600-30bc-11ea-8337-89a9ccf8db12.png)

![Inside2](https://user-images.githubusercontent.com/5429817/71840007-bcef3680-30bc-11ea-956d-d93180acc26e.png)

**Comment by Simonrazer** [comment]
Daaamn that looks good, is that in Eevee or Armory? I was able to build it on low quality settings as well by redoing the materials, but for me Armory seems to have gotten confused by something and the textures look very broken. Eevee looked fine, just low Res.

**Comment by Naxela** [comment]
This is just Eevee for now, baked with one 2K map @ medium settings (Took 5 minutes with GPU). I tried with Armory too, but I also got something that looked broken, although I thought it was just my own fault (as I'm updating [PPM](https://github.com/Naxela/PPM)) thinking it would look better with some colorgrading, but I'm not really sure what goes on with Armory

**Comment by Naxela** [comment]
Seems like Armory doesn't like multi-material objects, although solving that is easy - Just select all faces and separate by material - This works fine without breaking the individual material's lightmap setup:

![Lightmap](https://user-images.githubusercontent.com/5429817/71852362-d3a38680-30d8-11ea-80bf-818d8c4c065e.jpg)
