### ISSUE TITLE
Blender 2.90.1 crashes when trying to render the lightmaps

### ISSUE THREAD

**Issue by jure** [Naxela/The_Lightmapper#54]
Hi! Thank you for your hard work - this is a great add-on! I've been using it for some experiments and it worked nicely, but now it crashes Blender every time I try to render the lightmaps.

```
# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF685A656C2
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000001
	Parameters[1] : 0x0000000000000538


Stack trace:
blender.exe         :0x00007FF685A656B0  rtcSetDeviceMemoryMonitorFunction
blender.exe         :0x00007FF688A42AA0  ccl::BVHEmbree::build
blender.exe         :0x00007FF6859929B0  ccl::GeometryManager::device_update_bvh
blender.exe         :0x00007FF68598E7B0  ccl::GeometryManager::device_update
blender.exe         :0x00007FF685955DC0  ccl::Scene::device_update
blender.exe         :0x00007FF685969790  ccl::Session::update_scene
blender.exe         :0x00007FF68596BCC0  ccl::Session::run_cpu
blender.exe         :0x00007FF68596A620  ccl::Session::run
blender.exe         :0x00007FF687B131A0  ccl::thread::run
blender.exe         :0x00007FF685121450  std::thread::_Invoke<std::tuple<void * __ptr64 (__cdecl*)(void * __ptr64),ccl::thread * __ptr64>,0,
ucrtbase.dll        :0x00007FFBB2701430  configthreadlocale
KERNEL32.DLL        :0x00007FFBB2E17020  BaseThreadInitThunk
ntdll.dll           :0x00007FFBB4CDCEA0  RtlUserThreadStart
```

It works (continues to work) in another simpler scene, however. Any ideas?

Additionally, I'm unable to render with the GPU - it produces black lightmaps. Doubt it's related, but maybe useful information for debugging.

**Comment by Naxela** [comment]
Hi,

Thanks for trying out the addon!

Unfortunately the two recent Blender versions have turned up a series of strange bugs that I'm still trying to fix. As for the error you seem to be getting (EXCEPTION_ACCESS_VIOLATION), I stumple upon it from time to time, but I've yet to be able to figure out what exactly goes wrong. Do you have a lot of textures in your scene?

As for the black lightmaps when baking with the GPU, which settings are you building your lightmaps with?

Sadly, the only possible advice/fix I currently can give is to either try updating video drivers or try the 2.83 LTS version of Blender and see if that still crashes

**Comment by jure** [comment]
I have a few 6K textures, but nothing too crazy (unless 6K textures are crazy?). I'd be happy to email over a scene if you want. Also happy to help out with fixing some of these issues, if you're willing to assign some of them and perhaps give some guidance :)

The settings for GPU baking are all default, it doesn't work in any configuration that I've tried (NVIDIA 2080 Ti - Cycles on the GPU works fine otherwise). I'll try again with 2.83, thanks for the tip!

**Comment by Naxela** [comment]
I think 6K textures shouldn't be too bad, and with that GPU there shouldn't be an issue with VRAM (neither in Eevee nor during rendering, if you're getting the error in CPU mode). Are you able to bake with cycles when you're setting it up manually? I.e. a simple cube + plane setup with diffuse light baking or do you get the same error:

![billede](https://user-images.githubusercontent.com/5429817/101241330-507a1e80-36f5-11eb-8ea7-4b86774a8a92.png)

I think the GPU baking is a separate issue. Is your GPU set to use Cuda or Optix in the user preferences? Or do you get any console messages if you bake with GPU and toggle on verbose output?

Oh, and if you don't mind, you can send the scene with WeTransfer to: KleemannAlexander@gmail.com (Only if it's not too much of a hassle)

---

With that being said, I plan on doing some progress on adding support for baking on Octane Render, so if the problem persists, at least that would provide an alternative in the future for both CPU and GPU baking.

**Comment by jure** [comment]
Oh, interesting! So I tried to bake with Cycles in CPU mode directly, and it errored with a 'circular dependency' and crashed as well! Progress!

```Circular dependency for image "GroundPebbles006_NRM_4K.jpg" from object "Cube.002"  # Info```

So I'll spend some time debugging on my end!

Update: After resolving this issue, which is just me not understanding how baking textures work - it still crashes when using Cycles directly. However, it does not crash with the same scene in 2.91, so that's something! I think that's a Cycles bug that has since been resolved.

Your tip about OptiX and Cuda was helpful too. I've managed to get GPU baking working by selecting the CUDA system instead of OptiX. Is OptiX supposed to work?

Thank you so much for your help! I'm closing this as it seems to be a Cycles bug that has already been fixed in the latest version.

**Comment by Naxela** [comment]
Hi,

Does it mean that CPU baking in Blender 2.91 works for you with The lightmapper? I.e. So It's only a 2.90 issue? I did read in the tracker that there was some bugs that might have been related to that which were resolved.

As for the Cuda/Optix problem, it's true that Optix currently isn't available for baking in Blender (https://github.com/Naxela/The_Lightmapper/issues/43) although I'm crossing my fingers that the Blender dev team will add it in 2.92 as it does sound like it could give some decent speed improvements

But great to hear that it worked out!

**Comment by jure** [comment]
Yes, CPU baking works in Blender 2.91, at least in my case!

Hmm... Not sure if it's worth it, but is there an easy way to detect the currently selected GPU system and disable the GPU option in Lightmapper, if there's a known incompatibility?
