### ISSUE TITLE
GPU Rendering Issue

### ISSUE THREAD

**Issue by samevision** [Naxela/The_Lightmapper#56]
Hello,

I am playing around with TLM again and I encountered some problem with rendering the lightmaps with GPU. I would love to use the GPU with enabled OptiX as cycle render device. Unfortunately the rendering process finished after a few seconds and the lightmap is completely black.

Setting the cycles render device to none in blender preferences and enabling GPU in TLM settings works but it seems that still the CPU is used. It takes the same amount of time and the workload shows 100% CPU and nearly 0% GPU.

Am I doing something wrong? How am I able to fix this?

Best

**Comment by Naxela** [comment]
Hi,

Sadly, baking with Optix is not yet supported with Cycles: https://developer.blender.org/T80823 - As such it just leaves a black lightmap. The only thing I can recommend for now is to use Cuda or OpenCL for GPU devices until Blender adds support for that.

**Comment by Naxela** [comment]
Resolved by Blender defaulting to CUDA when using baking.
