### ISSUE TITLE
Lightmap ImageTexture Wrapping/Extension Mode Override

### ISSUE THREAD

**Issue by McKay42** [Naxela/The_Lightmapper#57]
Current default behavior:

![seam](https://user-images.githubusercontent.com/16856443/102075115-0fc18a00-3e06-11eb-873c-067d874574b2.PNG)

Notice the light bleeding from the left side of the room to the top right edge.
This is because the default texture wrapping mode is repeat (and because of how texture filtering works):

![node_repeat](https://user-images.githubusercontent.com/16856443/102075229-3e3f6500-3e06-11eb-9ab0-098a49cb762b.PNG)

If it is changed to extend (or clip) then the bleeding stops:

![node_extend](https://user-images.githubusercontent.com/16856443/102075848-29af9c80-3e07-11eb-9cec-d99229239419.PNG)

![noseam](https://user-images.githubusercontent.com/16856443/102075552-b1e17200-3e06-11eb-919e-7e76e47a18c9.PNG)

I've manually updated my /\<addon\>/utility/cycles/nodes.py to set `lightmapNode.extension = "EXTEND"`, but I think this would be nice to have as a global setting, as well as improve the out-of-the-box experience by making extend the default.

(Of course all of this is only relevant for previewing the lightmaps inside Blender, but still.)

**Comment by Naxela** [comment]
Hi, thanks for the input!

I hadn't thought of adding that as an option, but it was a good idea. I've added the option for select interpolation and extension/extrapolation in the main menu:

![billede](https://user-images.githubusercontent.com/5429817/102104593-a7d36980-3e2e-11eb-83de-5f29141028aa.png)

**Comment by McKay42** [comment]
> 
> I've added the option for select interpolation and extension/extrapolation in the main menu:

Thank you, that's perfect. I assume you want to leave issues open until a new release exists which contains them?

**Comment by Naxela** [comment]
Hi, 
Yeah, leaving it open for now would be fine as it would make it easier to check them off once I get to write the release notes for the next release

**Comment by Naxela** [comment]
Should be resolved in: https://github.com/Naxela/The_Lightmapper/commits/master
