### ISSUE TITLE
Baking lightmaps to export in GLTF-format for ThreeJS seems bugged

### ISSUE THREAD

**Issue by rienheuver** [Naxela/The_Lightmapper#58]
Hey there,
I've only just started using your library in Blender and from what I've seen so far it's incredible! I'm also quite a Blender novice since I'm really only using it for making assets to use in ThreeJS. My problem/bug:
I built a maze in blender and put some lights scattered throughout the maze. I baked everything, imported it in threejs and somehow the textures seem to be misplaced. I added my .blend-file and a video showcasing the odd-looking textures in ThreeJS in the zip below.
[lightmap-bug.zip](https://github.com/Naxela/The_Lightmapper/files/5742429/lightmap-bug.zip)

The baked textures look rather good in Blender. Is there something I'm doing wrong here? Would love to find out, because if I can get this to work it would be nothing short of amazing! I'm baking with the following settings:
- Device: GPU
- Quality: Medium
- Resolution scale: 1/1
- Baking mode: Foreground
- Caching mode: Copy
- Directional mode: None
- Lightmap Directory: Lightmaps
- Dilation margin: 4px
- Exposure Multiplier: 0.00
- Supersampling: None
- Denoise enabled

Please, if there is any more information or help I can give let me know, I'm very willing to help if I can.

Edit: possibly relevant information:
- OS: Linux
- Blender version: 2.91.0
- ThreeJS verison: 0.123.0
- GPU: Nvidia GTX1060

**Comment by Naxela** [comment]
Hi, it sounds like it could be a problem with uv channels, the Lightmapper normally creates a second uv channel called UVMap_Lightmap and specifies to use it in the blender material (its usually one of the material nodes to the left). I don't know three.js that well, but it should be possible to assign that second uv, since I'm sure gltf supports it and I think someone else had luck using three.js with the lightmapper too - I think this might be related, but I don't have too much insight in creating materials for in it: https://stackoverflow.com/questions/38166566/how-to-specify-uv-channels-for-different-maps-in-three-js

I hope this helps

**Comment by rienheuver** [comment]
Thanks for the quick reply and you couldn't be more right!
Just to make sure I understand your reply: Lightmapper generates a UV map of the object, which it needs to make a texture image to bake onto. However, that UV map is not correctly imported in ThreeJS?
What I do know for sure is that your guess is spot on ;-). I simply switched the UV map in Blender to the first one 'UVMap' and I see exactly the same 'artefacts' as I do in ThreeJS.
The link to StackOverflow you suggested wasn't much help to me unfortunately, but that's mostly because I understand at best half of what the answer is saying...

However, I found this answer which did exactly what I needed: https://discourse.threejs.org/t/why-is-uv-map-designed-in-blender-not-showing-up-correctly-in-gltf-glb-model-on-my-website/16988/4
The simple fix for me was to select every object that I'm using in ThreeJS and deleting that first UV map altogether. And it worked! The result is better than I dared to dream before I found your plugin. I'm ecstatic!

If I can be of any help, please let me know. I'd be more than willing to write some wiki on how to use this plugin for ThreeJS for example, or maybe do a tutorial-blogpost. Just let me know and thanks again!

**Comment by re1995** [comment]
hi when i delete the first UV map, it looks different an wrong in the blender and in three js! what is your suggestion?
