### ISSUE TITLE
How to use generated lightmaps in Unity?

### ISSUE THREAD

**Issue by tibor-vavra** [Naxela/The_Lightmapper#61]
Hi,

I like your plugin so much. I'm trying to use generated lightmaps in Unity but the result is so dark. Maybe I'm using it wrong. 
It is possible to generate just simple lightmaps without hdr information?

Thank you

**Comment by Naxela** [comment]
Hi, sorry for replying late

By default you can turn on the encoding to .exr files, which is the same format that Unity uses for baking it's own lightmaps, but if you just want basic png files, you can also use the aframe addon, which uses the lightmapper and converts to png files on it's own: https://silverslade.itch.io/a-frame-blender-exporter - Although basic png export is something I'm planning on adding in the future:

**Comment by Naxela** [comment]
Added a tutorial regarding this to the todo list:
https://github.com/Naxela/The_Lightmapper/wiki/%5BTodo%5D-Using-The-Lightmapper-with-Unity

**Comment by tibor-vavra** [comment]
Aframe blender export is a very nice idea as a complex solution. I figure it out in Unity, my problem was default lightning. I just needed to exclude loaded objects with lightmaps from lightning in the scene.

Thank you again for the help and your plugin
