### ISSUE TITLE
Can't bake with area lamps

### ISSUE THREAD

**Issue by Piflyer** [Naxela/The_Lightmapper#64]
I'm trying to use this addon to bake a scene, but I don't see any area lmaps being exported. I'm using the latest stable version.

**Comment by Naxela** [comment]
Hi,

Which version of Lightmapper and Blender are you using?

**Comment by Piflyer** [comment]
Hi,

It seems like even with the WIP 0.5, area lamps are not supported, unless I am mistaken. I am currently using Blender 2.91.2. It also seems like materials with a very high specular and metallic materials aren't baking in reflections. Is there a setting to bake both of those textures and the area lamp? Thanks.

**Comment by Piflyer** [comment]
Also, is there any plan to support Blender's sky textures?

**Comment by Naxela** [comment]
Hi,

Both sky textures and area lamps should work fine, basically anything that Cycles support should work (Apart from Optix):

Area Lamps:

![image](https://user-images.githubusercontent.com/5429817/105957416-85fa1300-6079-11eb-8795-ae27ad6994fa.png)

Sky textures (Nishita)

![image](https://user-images.githubusercontent.com/5429817/105957739-f2751200-6079-11eb-9263-60b7201a21ac.png)

As for specular textures, they should work just fine - As for metals, the lightmapper only bakes diffuse and indirect lighting information, not reflections (similar to how Unity and Unreal Engine does it), so for metallic objects I either recommend using some of the metallic clamping options, or skipping the metallic material under the material options:

![image](https://user-images.githubusercontent.com/5429817/105957957-3e27bb80-607a-11eb-88b5-f618cc5e4ffb.png)

**Comment by Naxela** [comment]
Should be fixed in: https://github.com/Naxela/The_Lightmapper/commit/7cdf23ff39c29598a1e47f94c34efab63df40e65
