### ISSUE TITLE
Export GLTF

### ISSUE THREAD

**Issue by re1995** [Naxela/The_Lightmapper#68]
please Help ME!
when i Export for GLTF for web, Baked LightMaps dont Export. What Can I do?

**Comment by Naxela** [comment]
The baked lightmaps are placed in a folder where your Blender file is located:

![image](https://user-images.githubusercontent.com/5429817/106737366-dbed2e80-6616-11eb-88b6-f9ffb996e475.png)

You probably need to reference the lightmap files manually, depending on which software you're using
