### ISSUE TITLE
Some weird pixel artefacts in simple bake

### ISSUE THREAD

**Issue by rienheuver** [Naxela/The_Lightmapper#69]
I baked a simple setup with some walls, a floor and a ceiling all with just a base color as material and the default lamp is also in the scene. When I bake the textures I get some strange pixel artefacts near the edge of the walls.
![image](https://user-images.githubusercontent.com/9960351/107118194-b6af2900-687f-11eb-9449-196ddf7b3483.png)

This seems like a bug to me, because I can't figure out what causes it. If you have any suggestions I'd be glad to hear them, the artefacts are quite noticeable when I view them in threejs.

Full blend file with materials packed:
[bake-testing.zip](https://github.com/Naxela/The_Lightmapper/files/5936804/bake-testing.zip)

**Comment by Naxela** [comment]
Hi, are you using integrated denoising? I get the same sometimes, and it seems they're more noticeable when using integrated denoising and low resolutions - what I would recommend is using either Oidn or Optix, plus using supersampling also seems to help on it

**Comment by rienheuver** [comment]
Yes I was, using oidn does indeed improve it. I then got some strange "shadow" pixels on the edges of my faces. I tried 4x supersampling after that and that fixed the shadow-bug. So thanks, problem solved!
