### ISSUE TITLE
Pre-packing issue

### ISSUE THREAD

**Issue by samevision** [Naxela/The_Lightmapper#77]
Hello,

thanks for the new version. I am glad that you are still working on this project.

Unfortunately I have still problems with pre-packing since I can't use my own uv maps. I have two objects, both of them have a second uv map ("UVMap_Lightmap"), I created an atlas group, I added both objects to the atlas group and choose as unwrap mode "Lightmap":

> enum "EDIT" not found in ('OBJECT')

If I choose "Smart Project" as unwrap mode it works fine. But I would like to use my own uv maps.

Am I doing something wrong?

Best

**Comment by Naxela** [comment]
Hi,

It seems you've found a bug, although I can't seem to reproduce it - although I think for what you want, the workflow is a little different.

If I understood you correctly, what you have are two objects with premade UV maps. You want to have those in the same atlas lightmap right?

What the **prepack method** does, is that it takes all your objects and runs your selected algorithm on them simultanously (in your case, Lightmap being the Lightmap pack function in Blender). Your own UV maps are overriden when using this.

What I think you want is the **postpack method** - It takes all your objects, uses the existing UV or creates a new one and bin packs them into the same atlas (provided your atlas is large enough).

The workflow is:
- Under the Atlas settings, select postpack and add a group of sufficient size (enough to contain your lightmap resolutions)
- Under Object settings, if you already have setup a UV or provided a custom UV channel, you can ignore these as it's just if not lightmap channel is detected. Toggle on Postpack Object and select your Atlas Group.
- When you bake now, it should be baked to the same atlas:

![Bake_atlas](https://user-images.githubusercontent.com/5429817/108983403-21899e00-768f-11eb-9160-0cf815a67009.jpg)

![bake_object](https://user-images.githubusercontent.com/5429817/108983414-23ebf800-768f-11eb-9a5e-2ec5ee627632.jpg)

![bake_together](https://user-images.githubusercontent.com/5429817/108983426-277f7f00-768f-11eb-97c0-286e3d09e90a.jpg)

![bake_uv](https://user-images.githubusercontent.com/5429817/108983440-29e1d900-768f-11eb-8df7-471ce7a69468.jpg)

But as I mentioned, you did seem to stumble upon a bug, as the object edit error is not supposed to happen.

Hope it helps!

**Comment by samevision** [comment]
Hello Naxela,

sorry for my late reply. It took some time to get some space to tackle this lightmap problem again. Thanks for your response!

I also experimented with post packing mode but I can say that I definitely want to use the prepacking mode because I don't want to pack multiple textures into one. As your image shows a lot of space is wasted since you pack all textures side by side.

Blender offers the nice feature to unwrap multiple objects at ones. So after just make a smart uv unwrap of both spheres I get this UV Map:

<img width="426" alt="tJ0Td4Eb15" src="https://user-images.githubusercontent.com/47099154/111870324-66e67600-8984-11eb-8503-003bd29724d6.png">

Now I want to bake the lightmap of both spheres due to this UV Map on one single texture. Am I able to do this anyhow?

Best

**Comment by Naxela** [comment]
Hi, I think I misunderstood you the first time around,

I think what you're seeking is the option **copy existing** under the atlas group tab (prepack):

![image](https://user-images.githubusercontent.com/5429817/111993793-5286b280-8b17-11eb-9a6f-6dfeb0698da5.png)

Below is an example of the spheres using an arbitrary manual UV map and baked together to the same prepacked lightmap:

![image](https://user-images.githubusercontent.com/5429817/111994467-1869e080-8b18-11eb-8e21-68ec9a250ade.png)

I don't remember exactly when I implemented the copy existing option, but it might have been after you initially asking your question, but I hope it does what you're seeking
